/**
 * Image pipeline — spec/assets.md §3.
 *
 * For every source image emits AVIF, WebP and JPEG at a ladder of widths, and
 * records a base64 LQIP and a dominant colour so a slide can paint before its
 * image lands. The reference gets all three free from its CDN; we generate them
 * at build time and commit the manifest, which keeps the site a static deploy
 * with no image service in front of it.
 *
 *   npm run images
 */
import sharp from 'sharp';
import { readdir, mkdir, writeFile, stat } from 'node:fs/promises';
import { join, basename, extname } from 'node:path';

const SRC = 'public/renders';
const OUT = 'public/img';

/** Width-based rather than DPR-based: fewer variants, and `sizes` is honest. */
const WIDTHS = {
  landscape: [640, 1024, 1440, 1920, 2440],
  portrait: [390, 640, 828, 1080],
  gallery: [640, 1024, 1600],
  floorplan: [1024, 1600, 2400],
  panel: [512, 1012],
};

const FORMATS = [
  ['avif', { quality: 50, effort: 5 }],
  ['webp', { quality: 72 }],
  ['jpg', { quality: 76, mozjpeg: true }],
];

async function variantsFor(file, kind, id) {
  const image = sharp(file);
  const meta = await image.metadata();
  const widths = WIDTHS[kind].filter((w) => w <= (meta.width ?? 0));
  if (widths.length === 0) widths.push(meta.width ?? 0);

  const srcset = {};
  let bytes = 0;
  for (const [fmt, opts] of FORMATS) {
    srcset[fmt] = [];
    for (const w of widths) {
      const name = `${id}-${w}.${fmt}`;
      const dest = join(OUT, kind, name);
      await sharp(file).resize({ width: w, withoutEnlargement: true })[fmt === 'jpg' ? 'jpeg' : fmt](opts).toFile(dest);
      bytes += (await stat(dest)).size;
      srcset[fmt].push({ w, url: `/img/${kind}/${name}` });
    }
  }

  // LQIP: a 16px-wide JPEG, inlined. Small enough to sit in the manifest.
  const lqipBuf = await sharp(file).resize({ width: 16 }).jpeg({ quality: 40 }).toBuffer();
  const lqip = `data:image/jpeg;base64,${lqipBuf.toString('base64')}`;

  // Dominant colour: average the image down to a single pixel.
  const [r, g, b] = await sharp(file).resize(1, 1, { fit: 'fill' }).raw().toBuffer();
  const dominant = `#${[r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('')}`;

  return {
    id, kind, width: meta.width, height: meta.height,
    aspect: +(meta.width / meta.height).toFixed(4),
    srcset, lqip, dominant, generatedBytes: bytes,
  };
}

const jobs = [
  ['landscape', join(SRC, 'slides/landscape')],
  ['portrait', join(SRC, 'slides/portrait')],
  ['gallery', join(SRC, 'gallery')],
  ['floorplan', join(SRC, 'floorplans')],
];

const manifest = {};
let sourceBytes = 0;
let outBytes = 0;

for (const [kind, dir] of jobs) {
  await mkdir(join(OUT, kind), { recursive: true });
  for (const f of (await readdir(dir)).filter((n) => /\.(jpe?g|png)$/i.test(n))) {
    const file = join(dir, f);
    sourceBytes += (await stat(file)).size;
    const id = basename(f, extname(f));
    const v = await variantsFor(file, kind, id);
    outBytes += v.generatedBytes;
    manifest[`${kind}/${id}`] = v;
    process.stdout.write(`  ${kind}/${id} ${v.width}x${v.height}\n`);
  }
}

// Panel images (menu background + overview axonometric)
await mkdir(join(OUT, 'panel'), { recursive: true });
for (const id of ['menu-panel', 'overview-axon']) {
  const file = join(SRC, 'slides', `${id}.jpg`);
  sourceBytes += (await stat(file)).size;
  const v = await variantsFor(file, 'panel', id);
  outBytes += v.generatedBytes;
  manifest[`panel/${id}`] = v;
  process.stdout.write(`  panel/${id} ${v.width}x${v.height}\n`);
}

const header = `// GENERATED by scripts/build-images.mjs — do not edit.
// Run \`npm run images\` after changing anything in public/renders/.
export interface ImageVariant { w: number; url: string }
export interface ImageEntry {
  id: string; kind: string; width: number; height: number; aspect: number;
  srcset: { avif: ImageVariant[]; webp: ImageVariant[]; jpg: ImageVariant[] };
  lqip: string; dominant: string;
}
export const images: Record<string, ImageEntry> = `;

await writeFile(
  'src/data/images.generated.ts',
  header + JSON.stringify(
    Object.fromEntries(Object.entries(manifest).map(([k, v]) => {
      const { generatedBytes, ...rest } = v;
      return [k, rest];
    })), null, 1) + ' as const;\n',
);

console.log(`\nsources   ${(sourceBytes / 1e6).toFixed(1)} MB across ${Object.keys(manifest).length} images`);
console.log(`generated ${(outBytes / 1e6).toFixed(1)} MB of variants`);
