// GENERATED by scripts/build-images.mjs — do not edit.
// Run `npm run images` after changing anything in public/renders/.
export interface ImageVariant { w: number; url: string }
export interface ImageEntry {
  id: string; kind: string; width: number; height: number; aspect: number;
  srcset: { avif: ImageVariant[]; webp: ImageVariant[]; jpg: ImageVariant[] };
  lqip: string; dominant: string;
}
export const images: Record<string, ImageEntry> = {
 "landscape/00-hero": {
  "id": "00-hero",
  "kind": "landscape",
  "width": 2440,
  "height": 1626,
  "aspect": 1.5006,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/landscape/00-hero-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/landscape/00-hero-1024.avif"
    },
    {
     "w": 1440,
     "url": "/img/landscape/00-hero-1440.avif"
    },
    {
     "w": 1920,
     "url": "/img/landscape/00-hero-1920.avif"
    },
    {
     "w": 2440,
     "url": "/img/landscape/00-hero-2440.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/landscape/00-hero-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/landscape/00-hero-1024.webp"
    },
    {
     "w": 1440,
     "url": "/img/landscape/00-hero-1440.webp"
    },
    {
     "w": 1920,
     "url": "/img/landscape/00-hero-1920.webp"
    },
    {
     "w": 2440,
     "url": "/img/landscape/00-hero-2440.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/landscape/00-hero-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/landscape/00-hero-1024.jpg"
    },
    {
     "w": 1440,
     "url": "/img/landscape/00-hero-1440.jpg"
    },
    {
     "w": 1920,
     "url": "/img/landscape/00-hero-1920.jpg"
    },
    {
     "w": 2440,
     "url": "/img/landscape/00-hero-2440.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAALABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAECBf/EACEQAAIBAwMFAAAAAAAAAAAAAAECAwAEERMhMQUSgZHB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABgRAQADAQAAAAAAAAAAAAAAAAEAAhES/9oADAMBAAIRAxEAPwBXEFraiTTDNJntGeFP2syHqd1Bcu8bgMwKDbjxRBI8mVdiwGealEUaxxuACPdNVjkrWf/Z",
  "dominant": "#5c605f"
 },
 "landscape/01-first-floor": {
  "id": "01-first-floor",
  "kind": "landscape",
  "width": 2400,
  "height": 1350,
  "aspect": 1.7778,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/landscape/01-first-floor-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/landscape/01-first-floor-1024.avif"
    },
    {
     "w": 1440,
     "url": "/img/landscape/01-first-floor-1440.avif"
    },
    {
     "w": 1920,
     "url": "/img/landscape/01-first-floor-1920.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/landscape/01-first-floor-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/landscape/01-first-floor-1024.webp"
    },
    {
     "w": 1440,
     "url": "/img/landscape/01-first-floor-1440.webp"
    },
    {
     "w": 1920,
     "url": "/img/landscape/01-first-floor-1920.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/landscape/01-first-floor-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/landscape/01-first-floor-1024.jpg"
    },
    {
     "w": 1440,
     "url": "/img/landscape/01-first-floor-1440.jpg"
    },
    {
     "w": 1920,
     "url": "/img/landscape/01-first-floor-1920.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIF/8QAHhABAAIBBAMAAAAAAAAAAAAAAQAxAwIEERMScrH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAFREBAQAAAAAAAAAAAAAAAAAAAAH/2gAMAwEAAhEDEQA/ANF04+zxM1tETZK4juR18PJUnBT7P2KUwS1//9k=",
  "dominant": "#c2ae94"
 },
 "landscape/02-second-floor": {
  "id": "02-second-floor",
  "kind": "landscape",
  "width": 2400,
  "height": 1350,
  "aspect": 1.7778,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/landscape/02-second-floor-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/landscape/02-second-floor-1024.avif"
    },
    {
     "w": 1440,
     "url": "/img/landscape/02-second-floor-1440.avif"
    },
    {
     "w": 1920,
     "url": "/img/landscape/02-second-floor-1920.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/landscape/02-second-floor-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/landscape/02-second-floor-1024.webp"
    },
    {
     "w": 1440,
     "url": "/img/landscape/02-second-floor-1440.webp"
    },
    {
     "w": 1920,
     "url": "/img/landscape/02-second-floor-1920.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/landscape/02-second-floor-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/landscape/02-second-floor-1024.jpg"
    },
    {
     "w": 1440,
     "url": "/img/landscape/02-second-floor-1440.jpg"
    },
    {
     "w": 1920,
     "url": "/img/landscape/02-second-floor-1920.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwT/xAAhEAABAwMEAwAAAAAAAAAAAAABAAIDBBIxBSEyNHKRsf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCxtQwSSsdc2w7l2EVTIySC8A4wU+ocPfxTzdYeKIj/2Q==",
  "dominant": "#a69684"
 },
 "landscape/03-third-floor": {
  "id": "03-third-floor",
  "kind": "landscape",
  "width": 3200,
  "height": 1800,
  "aspect": 1.7778,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/landscape/03-third-floor-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/landscape/03-third-floor-1024.avif"
    },
    {
     "w": 1440,
     "url": "/img/landscape/03-third-floor-1440.avif"
    },
    {
     "w": 1920,
     "url": "/img/landscape/03-third-floor-1920.avif"
    },
    {
     "w": 2440,
     "url": "/img/landscape/03-third-floor-2440.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/landscape/03-third-floor-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/landscape/03-third-floor-1024.webp"
    },
    {
     "w": 1440,
     "url": "/img/landscape/03-third-floor-1440.webp"
    },
    {
     "w": 1920,
     "url": "/img/landscape/03-third-floor-1920.webp"
    },
    {
     "w": 2440,
     "url": "/img/landscape/03-third-floor-2440.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/landscape/03-third-floor-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/landscape/03-third-floor-1024.jpg"
    },
    {
     "w": 1440,
     "url": "/img/landscape/03-third-floor-1440.jpg"
    },
    {
     "w": 1920,
     "url": "/img/landscape/03-third-floor-1920.jpg"
    },
    {
     "w": 2440,
     "url": "/img/landscape/03-third-floor-2440.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIE/8QAIRAAAQIEBwAAAAAAAAAAAAAAAQADAgQREgUxMjM0QVH/xAAUAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8ARu2Jy0E6a59ocQhAaIBNLvVpltlRPcZBf//Z",
  "dominant": "#89847e"
 },
 "landscape/gate": {
  "id": "gate",
  "kind": "landscape",
  "width": 1440,
  "height": 1762,
  "aspect": 0.8173,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/landscape/gate-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/landscape/gate-1024.avif"
    },
    {
     "w": 1440,
     "url": "/img/landscape/gate-1440.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/landscape/gate-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/landscape/gate-1024.webp"
    },
    {
     "w": 1440,
     "url": "/img/landscape/gate-1440.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/landscape/gate-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/landscape/gate-1024.jpg"
    },
    {
     "w": 1440,
     "url": "/img/landscape/gate-1440.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAUABADASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAAMBAgb/xAAeEAACAgIDAQEAAAAAAAAAAAABAgMRAAQSITEiUf/EABUBAQEAAAAAAAAAAAAAAAAAAAAD/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AzsCsiiVOqNY50bYWVybEZAFD3LaxURqr3RvzGWqxui3X4cmonQhWeVUe64k9HHb+skHApy+gbs4YYH//2Q==",
  "dominant": "#4f392d"
 },
 "portrait/00-hero": {
  "id": "00-hero",
  "kind": "portrait",
  "width": 824,
  "height": 1430,
  "aspect": 0.5762,
  "srcset": {
   "avif": [
    {
     "w": 390,
     "url": "/img/portrait/00-hero-390.avif"
    },
    {
     "w": 640,
     "url": "/img/portrait/00-hero-640.avif"
    }
   ],
   "webp": [
    {
     "w": 390,
     "url": "/img/portrait/00-hero-390.webp"
    },
    {
     "w": 640,
     "url": "/img/portrait/00-hero-640.webp"
    }
   ],
   "jpg": [
    {
     "w": 390,
     "url": "/img/portrait/00-hero-390.jpg"
    },
    {
     "w": 640,
     "url": "/img/portrait/00-hero-640.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAcABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMEBf/EACUQAAIBAwIFBQAAAAAAAAAAAAECAwAEERIhIjEyUcETFDNBgf/EABYBAQEBAAAAAAAAAAAAAAAAAAECA//EABoRAQACAwEAAAAAAAAAAAAAAAEAAgMRISL/2gAMAwEAAhEDEQA/AFz2ohcgIFwAASdWdtye/ik3N9CimBY9L7EyA5H52or24a8gYzN6I1HT3Cg+ayLn55ADsDgVKjbkTFo9S5zGI8yM0nEeW31UVzj3EhJHVVjSaU2ROsjlSLiNcNLjiY70UJref//Z",
  "dominant": "#60524a"
 },
 "portrait/01-first-floor": {
  "id": "01-first-floor",
  "kind": "portrait",
  "width": 777,
  "height": 1350,
  "aspect": 0.5756,
  "srcset": {
   "avif": [
    {
     "w": 390,
     "url": "/img/portrait/01-first-floor-390.avif"
    },
    {
     "w": 640,
     "url": "/img/portrait/01-first-floor-640.avif"
    }
   ],
   "webp": [
    {
     "w": 390,
     "url": "/img/portrait/01-first-floor-390.webp"
    },
    {
     "w": 640,
     "url": "/img/portrait/01-first-floor-640.webp"
    }
   ],
   "jpg": [
    {
     "w": 390,
     "url": "/img/portrait/01-first-floor-390.jpg"
    },
    {
     "w": 640,
     "url": "/img/portrait/01-first-floor-640.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAcABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMC/8QAIxAAAgIBAwMFAAAAAAAAAAAAAQIAEQMEEyEFMUESQmFxgf/EABUBAQEAAAAAAAAAAAAAAAAAAAAD/8QAFREBAQAAAAAAAAAAAAAAAAAAAAH/2gAMAwEAAhEDEQA/AG7rWCTQl0dWFggj7k9ZhXHpnYE2VP5x4g+h49xsm41gVUjFT3fe0gJXuDwZDRLkwOSy2pHt8RgA9MyFA7cD4gf/2Q==",
  "dominant": "#b9a58d"
 },
 "portrait/02-second-floor": {
  "id": "02-second-floor",
  "kind": "portrait",
  "width": 777,
  "height": 1350,
  "aspect": 0.5756,
  "srcset": {
   "avif": [
    {
     "w": 390,
     "url": "/img/portrait/02-second-floor-390.avif"
    },
    {
     "w": 640,
     "url": "/img/portrait/02-second-floor-640.avif"
    }
   ],
   "webp": [
    {
     "w": 390,
     "url": "/img/portrait/02-second-floor-390.webp"
    },
    {
     "w": 640,
     "url": "/img/portrait/02-second-floor-640.webp"
    }
   ],
   "jpg": [
    {
     "w": 390,
     "url": "/img/portrait/02-second-floor-390.jpg"
    },
    {
     "w": 640,
     "url": "/img/portrait/02-second-floor-640.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAcABADASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAgQAAQMF/8QAIBAAAgMAAQQDAAAAAAAAAAAAAQIAAxEEEkFRoSExYf/EABcBAAMBAAAAAAAAAAAAAAAAAAABAgP/xAAWEQEBAQAAAAAAAAAAAAAAAAAAARH/2gAMAwEAAhEDEQA/AOoTAYEyPZTWwN7sqEfa+ZSvxn68Z2zcwH3M8XpLl81S7VitASQBq777Q625FYATpwfnxMRUj3szKCRmHxHQMwdoSnY//9k=",
  "dominant": "#a99b8c"
 },
 "portrait/03-third-floor": {
  "id": "03-third-floor",
  "kind": "portrait",
  "width": 1037,
  "height": 1800,
  "aspect": 0.5761,
  "srcset": {
   "avif": [
    {
     "w": 390,
     "url": "/img/portrait/03-third-floor-390.avif"
    },
    {
     "w": 640,
     "url": "/img/portrait/03-third-floor-640.avif"
    },
    {
     "w": 828,
     "url": "/img/portrait/03-third-floor-828.avif"
    }
   ],
   "webp": [
    {
     "w": 390,
     "url": "/img/portrait/03-third-floor-390.webp"
    },
    {
     "w": 640,
     "url": "/img/portrait/03-third-floor-640.webp"
    },
    {
     "w": 828,
     "url": "/img/portrait/03-third-floor-828.webp"
    }
   ],
   "jpg": [
    {
     "w": 390,
     "url": "/img/portrait/03-third-floor-390.jpg"
    },
    {
     "w": 640,
     "url": "/img/portrait/03-third-floor-640.jpg"
    },
    {
     "w": 828,
     "url": "/img/portrait/03-third-floor-828.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAcABADASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAQIAAwT/xAAkEAACAgEDAgcAAAAAAAAAAAABAgARAwQSURMhIiMxMnGBkf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ALlbJ36ibDxEOXMoDNhIUkC75mrUL4h8QaoeRjHLLJCjauAS1GomfaUQWSQwqu8dlW/aPyRQB6KB9S0f/9k=",
  "dominant": "#9a9997"
 },
 "portrait/gate": {
  "id": "gate",
  "kind": "portrait",
  "width": 1015,
  "height": 1762,
  "aspect": 0.576,
  "srcset": {
   "avif": [
    {
     "w": 390,
     "url": "/img/portrait/gate-390.avif"
    },
    {
     "w": 640,
     "url": "/img/portrait/gate-640.avif"
    },
    {
     "w": 828,
     "url": "/img/portrait/gate-828.avif"
    }
   ],
   "webp": [
    {
     "w": 390,
     "url": "/img/portrait/gate-390.webp"
    },
    {
     "w": 640,
     "url": "/img/portrait/gate-640.webp"
    },
    {
     "w": 828,
     "url": "/img/portrait/gate-828.webp"
    }
   ],
   "jpg": [
    {
     "w": 390,
     "url": "/img/portrait/gate-390.jpg"
    },
    {
     "w": 640,
     "url": "/img/portrait/gate-640.jpg"
    },
    {
     "w": 828,
     "url": "/img/portrait/gate-828.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAcABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwEG/8QAJBAAAgICAQIHAQAAAAAAAAAAAQIDEQAEEhMhIjEyUVJhYqH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAA//EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oADAMBAAIRAxEAPwDPRF9dwwFh6AF40hknmGvVGrJu+2IUDqFHmACP7l006c7M/qIIo+2TVRJWSTw/EX2ymU87JBv6742jrxzySdQE8VFUax9vTij1y6huQ/ROCv/Z",
  "dominant": "#564032"
 },
 "gallery/ENT-004-001": {
  "id": "ENT-004-001",
  "kind": "gallery",
  "width": 2400,
  "height": 1350,
  "aspect": 1.7778,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-004-001-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-004-001-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-004-001-1600.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-004-001-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-004-001-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-004-001-1600.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-004-001-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-004-001-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-004-001-1600.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMF/8QAHxAAAgEEAgMAAAAAAAAAAAAAAQIAAwQRISMyM3Fy/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ANIUqauGOd6hbtOCthsgqYgdR7krjwv8mGR//9k=",
  "dominant": "#ae9e8c"
 },
 "gallery/ENT-005-002": {
  "id": "ENT-005-002",
  "kind": "gallery",
  "width": 2400,
  "height": 1350,
  "aspect": 1.7778,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-005-002-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-005-002-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-005-002-1600.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-005-002-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-005-002-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-005-002-1600.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-005-002-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-005-002-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-005-002-1600.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgMF/8QAJBAAAQMDAQkAAAAAAAAAAAAAAQACEQMEEgUUITI0UWFygcH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFREBAQAAAAAAAAAAAAAAAAAAAEH/2gAMAwEAAhEDEQA/ANerIuHS7FuIjud8/ENKFxtRfXcS3AgdJkJ1eY9BWs+N3kUaUf/Z",
  "dominant": "#beb6ae"
 },
 "gallery/ENT-006-003": {
  "id": "ENT-006-003",
  "kind": "gallery",
  "width": 2400,
  "height": 1350,
  "aspect": 1.7778,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-006-003-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-006-003-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-006-003-1600.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-006-003-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-006-003-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-006-003-1600.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-006-003-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-006-003-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-006-003-1600.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAEC/8QAIRAAAQMCBwEAAAAAAAAAAAAAAQACAxFBBBIiMjNhcYH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AdMXNjcYXaxS3aRgM0kIdMQX3p6sHjVh3P+Ik/9k=",
  "dominant": "#b5ada6"
 },
 "gallery/ENT-007-004": {
  "id": "ENT-007-004",
  "kind": "gallery",
  "width": 2072,
  "height": 1350,
  "aspect": 1.5348,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-007-004-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-007-004-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-007-004-1600.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-007-004-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-007-004-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-007-004-1600.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-007-004-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-007-004-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-007-004-1600.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAKABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAQIF/8QAHBABAAIDAAMAAAAAAAAAAAAAAQIRABIhMTJC/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ANScvR2HtLfjmMoVctvm8kACisBeltYSf//Z",
  "dominant": "#bab0a6"
 },
 "gallery/ENT-008-008": {
  "id": "ENT-008-008",
  "kind": "gallery",
  "width": 2400,
  "height": 1350,
  "aspect": 1.7778,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-008-008-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-008-008-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-008-008-1600.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-008-008-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-008-008-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-008-008-1600.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-008-008-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-008-008-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-008-008-1600.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EACIQAAIBAwIHAAAAAAAAAAAAAAECEQADIQQzBRIiMVFysf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAVEQEBAAAAAAAAAAAAAAAAAAAAAf/aAAwDAQACEQMRAD8AV1JVbZCHleDGe5iiuIr1ITOUzHmkr229HarZHoPtESP/2Q==",
  "dominant": "#aa9884"
 },
 "gallery/ENT-009-009": {
  "id": "ENT-009-009",
  "kind": "gallery",
  "width": 2400,
  "height": 1350,
  "aspect": 1.7778,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-009-009-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-009-009-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-009-009-1600.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-009-009-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-009-009-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-009-009-1600.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/gallery/ENT-009-009-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/gallery/ENT-009-009-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/gallery/ENT-009-009-1600.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgQG/8QAIBAAAQMCBwAAAAAAAAAAAAAAAgABAxESBDEyM0Fxcv/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAVEQEBAAAAAAAAAAAAAAAAAAAAEf/aAAwDAQACEQMRAD8A0JSOBVGl3FURmaUb2fNGXU3SnwW2Xp0Kb//Z",
  "dominant": "#d7cdc1"
 },
 "gallery/INT-003-000": {
  "id": "INT-003-000",
  "kind": "gallery",
  "width": 2400,
  "height": 1350,
  "aspect": 1.7778,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/gallery/INT-003-000-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-003-000-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-003-000-1600.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/gallery/INT-003-000-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-003-000-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-003-000-1600.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/gallery/INT-003-000-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-003-000-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-003-000-1600.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwEC/8QAHRAAAgICAwEAAAAAAAAAAAAAAQMCEQASBDRxMf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AZGquESWGE96iSLFZtDwyoyvevtUJeYDellV1leZM3//Z",
  "dominant": "#9c9183"
 },
 "gallery/INT-004-001": {
  "id": "INT-004-001",
  "kind": "gallery",
  "width": 2400,
  "height": 1350,
  "aspect": 1.7778,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/gallery/INT-004-001-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-004-001-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-004-001-1600.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/gallery/INT-004-001-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-004-001-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-004-001-1600.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/gallery/INT-004-001-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-004-001-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-004-001-1600.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAL/xAAhEAACAgECBwAAAAAAAAAAAAABAgARIQNxEhMxMjNBsf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFhEAAwAAAAAAAAAAAAAAAAAAAAEx/9oADAMBAAIRAxEAPwB7tTKNMXnOeglo453D6ItbFYgm7l3HyI0fIuxkuiof/9k=",
  "dominant": "#aea89d"
 },
 "gallery/INT-005-002": {
  "id": "INT-005-002",
  "kind": "gallery",
  "width": 2400,
  "height": 1350,
  "aspect": 1.7778,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/gallery/INT-005-002-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-005-002-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-005-002-1600.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/gallery/INT-005-002-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-005-002-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-005-002-1600.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/gallery/INT-005-002-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-005-002-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-005-002-1600.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwT/xAAhEAACAgECBwAAAAAAAAAAAAABAgADEQQxEyEiMzRxwf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAVEQEBAAAAAAAAAAAAAAAAAAAAAf/aAAwDAQACEQMRAD8Ar09rHiGy0hQOk784mnvLWsjsSd1OMZkq+JHTvU+vkMJ//9k=",
  "dominant": "#a69e98"
 },
 "gallery/INT-007-008": {
  "id": "INT-007-008",
  "kind": "gallery",
  "width": 2400,
  "height": 1350,
  "aspect": 1.7778,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/gallery/INT-007-008-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-007-008-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-007-008-1600.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/gallery/INT-007-008-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-007-008-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-007-008-1600.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/gallery/INT-007-008-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-007-008-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-007-008-1600.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMF/8QAIRAAAgEDAwUAAAAAAAAAAAAAAQIRAAMEEiExMzRhcXL/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFREBAQAAAAAAAAAAAAAAAAAAABH/2gAMAwEAAhEDEQA/ANTK1osW3UMORI4ol2wb6gZFwoVbaRMiPFSzu5b5FLweknujCf/Z",
  "dominant": "#ada296"
 },
 "gallery/INT-017-027": {
  "id": "INT-017-027",
  "kind": "gallery",
  "width": 2400,
  "height": 1800,
  "aspect": 1.3333,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/gallery/INT-017-027-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-017-027-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-017-027-1600.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/gallery/INT-017-027-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-017-027-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-017-027-1600.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/gallery/INT-017-027-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-017-027-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-017-027-1600.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAP/xAAfEAACAQQCAwAAAAAAAAAAAAABAhEAAxIhBBQxQZH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AdcbBjok4zAqCT2QSCMxEH7TXsJdYs0z40aN1bdrkZqWk+idCgT//2Q==",
  "dominant": "#a29b90"
 },
 "gallery/INT-019-032": {
  "id": "INT-019-032",
  "kind": "gallery",
  "width": 2400,
  "height": 1800,
  "aspect": 1.3333,
  "srcset": {
   "avif": [
    {
     "w": 640,
     "url": "/img/gallery/INT-019-032-640.avif"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-019-032-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-019-032-1600.avif"
    }
   ],
   "webp": [
    {
     "w": 640,
     "url": "/img/gallery/INT-019-032-640.webp"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-019-032-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-019-032-1600.webp"
    }
   ],
   "jpg": [
    {
     "w": 640,
     "url": "/img/gallery/INT-019-032-640.jpg"
    },
    {
     "w": 1024,
     "url": "/img/gallery/INT-019-032-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/gallery/INT-019-032-1600.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIE/8QAHxAAAgEEAgMAAAAAAAAAAAAAAQIRAAMSIQQxUVKx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAVEQEBAAAAAAAAAAAAAAAAAAAAEf/aAAwDAQACEQMRAD8AbfHxVTGCAR5Jp7TPcsZv7D7W3FVWAo32Y7qLigLA0JGqmF//2Q==",
  "dominant": "#aaa59a"
 },
 "floorplan/01-first-floor": {
  "id": "01-first-floor",
  "kind": "floorplan",
  "width": 4320,
  "height": 1284,
  "aspect": 3.3645,
  "srcset": {
   "avif": [
    {
     "w": 1024,
     "url": "/img/floorplan/01-first-floor-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/01-first-floor-1600.avif"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/01-first-floor-2400.avif"
    }
   ],
   "webp": [
    {
     "w": 1024,
     "url": "/img/floorplan/01-first-floor-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/01-first-floor-1600.webp"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/01-first-floor-2400.webp"
    }
   ],
   "jpg": [
    {
     "w": 1024,
     "url": "/img/floorplan/01-first-floor-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/01-first-floor-1600.jpg"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/01-first-floor-2400.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAFABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIG/8QAHRAAAgEEAwAAAAAAAAAAAAAAAAMBAhESISJRcf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDStbNLqotM77KW7K3HfoAH/9k=",
  "dominant": "#e6e6e6"
 },
 "floorplan/02-second-floor": {
  "id": "02-second-floor",
  "kind": "floorplan",
  "width": 4207,
  "height": 1440,
  "aspect": 2.9215,
  "srcset": {
   "avif": [
    {
     "w": 1024,
     "url": "/img/floorplan/02-second-floor-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/02-second-floor-1600.avif"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/02-second-floor-2400.avif"
    }
   ],
   "webp": [
    {
     "w": 1024,
     "url": "/img/floorplan/02-second-floor-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/02-second-floor-1600.webp"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/02-second-floor-2400.webp"
    }
   ],
   "jpg": [
    {
     "w": 1024,
     "url": "/img/floorplan/02-second-floor-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/02-second-floor-1600.jpg"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/02-second-floor-2400.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAFABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIG/8QAGxAAAQUBAQAAAAAAAAAAAAAAAQACAyFBEjH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A0z5i2YgDwnVcMnZbV3qIg//Z",
  "dominant": "#ededed"
 },
 "floorplan/03-third-floor": {
  "id": "03-third-floor",
  "kind": "floorplan",
  "width": 4408,
  "height": 1152,
  "aspect": 3.8264,
  "srcset": {
   "avif": [
    {
     "w": 1024,
     "url": "/img/floorplan/03-third-floor-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/03-third-floor-1600.avif"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/03-third-floor-2400.avif"
    }
   ],
   "webp": [
    {
     "w": 1024,
     "url": "/img/floorplan/03-third-floor-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/03-third-floor-1600.webp"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/03-third-floor-2400.webp"
    }
   ],
   "jpg": [
    {
     "w": 1024,
     "url": "/img/floorplan/03-third-floor-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/03-third-floor-1600.jpg"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/03-third-floor-2400.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAEABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIG/8QAGhABAAIDAQAAAAAAAAAAAAAAAQARAyExQf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDVgOVsOvhKwgVQbL5EQP/Z",
  "dominant": "#ededed"
 },
 "floorplan/04-fourth-floor": {
  "id": "04-fourth-floor",
  "kind": "floorplan",
  "width": 4303,
  "height": 960,
  "aspect": 4.4823,
  "srcset": {
   "avif": [
    {
     "w": 1024,
     "url": "/img/floorplan/04-fourth-floor-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/04-fourth-floor-1600.avif"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/04-fourth-floor-2400.avif"
    }
   ],
   "webp": [
    {
     "w": 1024,
     "url": "/img/floorplan/04-fourth-floor-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/04-fourth-floor-1600.webp"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/04-fourth-floor-2400.webp"
    }
   ],
   "jpg": [
    {
     "w": 1024,
     "url": "/img/floorplan/04-fourth-floor-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/04-fourth-floor-1600.jpg"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/04-fourth-floor-2400.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAEABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAEG/8QAHRAAAgEEAwAAAAAAAAAAAAAAAAECAxESQSFRYf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDW4xzfG+2WmlFu2vQAP//Z",
  "dominant": "#f0f0f0"
 },
 "floorplan/05-roof": {
  "id": "05-roof",
  "kind": "floorplan",
  "width": 4178,
  "height": 1144,
  "aspect": 3.6521,
  "srcset": {
   "avif": [
    {
     "w": 1024,
     "url": "/img/floorplan/05-roof-1024.avif"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/05-roof-1600.avif"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/05-roof-2400.avif"
    }
   ],
   "webp": [
    {
     "w": 1024,
     "url": "/img/floorplan/05-roof-1024.webp"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/05-roof-1600.webp"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/05-roof-2400.webp"
    }
   ],
   "jpg": [
    {
     "w": 1024,
     "url": "/img/floorplan/05-roof-1024.jpg"
    },
    {
     "w": 1600,
     "url": "/img/floorplan/05-roof-1600.jpg"
    },
    {
     "w": 2400,
     "url": "/img/floorplan/05-roof-2400.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAEABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAGRABAAMBAQAAAAAAAAAAAAAAAQACESED/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ANZ6V4opKUMN17EQP//Z",
  "dominant": "#f2f2f2"
 },
 "panel/menu-panel": {
  "id": "menu-panel",
  "kind": "panel",
  "width": 1012,
  "height": 1350,
  "aspect": 0.7496,
  "srcset": {
   "avif": [
    {
     "w": 512,
     "url": "/img/panel/menu-panel-512.avif"
    },
    {
     "w": 1012,
     "url": "/img/panel/menu-panel-1012.avif"
    }
   ],
   "webp": [
    {
     "w": 512,
     "url": "/img/panel/menu-panel-512.webp"
    },
    {
     "w": 1012,
     "url": "/img/panel/menu-panel-1012.webp"
    }
   ],
   "jpg": [
    {
     "w": 512,
     "url": "/img/panel/menu-panel-512.jpg"
    },
    {
     "w": 1012,
     "url": "/img/panel/menu-panel-1012.jpg"
    }
   ]
  },
  "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAVABADASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAABQACBP/EACAQAAICAAYDAAAAAAAAAAAAAAERAAIDBBIhIjEFYZH/xAAVAQEBAAAAAAAAAAAAAAAAAAACAP/EABYRAQEBAAAAAAAAAAAAAAAAAAABIf/aAAwDAQACEQMRAD8AVGKdJKZAZnFfylVwERsndVXHuDjKWSBoQvfcBExghgkuZ1VwcxTTQb7fZSkU1//Z",
  "dominant": "#b0a49a"
 }
} as const;
